services:
  backend:
    build: ./backend
    ports:
      - "6991:6991"
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src